#!/bin/bash
echo "🚀 Quick Vercel Deployment"
echo ""
echo "Step 1: Install Vercel CLI (if needed)"
echo "  npm install -g vercel"
echo ""
echo "Step 2: Login"
echo "  vercel login"
echo ""
echo "Step 3: Deploy"
echo "  vercel"
echo ""
echo "Step 4: Deploy to production"
echo "  vercel --prod"
echo ""
echo "Files ready:"
echo "  ✓ vercel.json"
echo "  ✓ api/index.py"
echo "  ✓ requirements.txt"
echo ""
echo "Make sure your data files (1_ab.txt, 2_ec.txt, 3_eb.txt) are in the repo!"
